### PR TITLE
Fix hosts source typo

### PR DESCRIPTION
**Pull request by 0-kaladin**
All tests are good now.  Can TAG at will.

### CODE REVIEW

**Comment by 0-kaladin** [comment]
@dschuermann f-droid hasn't built 3.0.1 yet, did I mess up the tag formatting for them to grab it?

**Comment by dschuermann** [comment]
Looks like they don't have gradle 2.5^^ See https://f-droid.org/wiki/page/org.adaway/lastbuild_53

**Comment by dschuermann** [comment]
I wrote them on IRC, maybe they will update the build server

**Comment by 0-kaladin** [comment]
@dschuermann looks like they did, thanks!
https://gitlab.com/fdroid/fdroidserver/issues/108

**Comment by 0-kaladin** [comment]
@dschuermann weird seemed to still fail this morning.

**Comment by dschuermann** [comment]
@0-kaladin It now succeeded

**Pull request merged**
