### PR TITLE
Host source

### PR DESCRIPTION
**Pull request by 0-kaladin**
update hosts-file.net and prep for a 3.0.1 release

### CODE REVIEW

**Comment by dschuermann** [comment]
Great work!

**Comment by dschuermann** [comment]
Ok, let me tag a new version

**Comment by dschuermann** [comment]
done

**Comment by 0-kaladin** [comment]
Clean install looks good but getting crash on an upgrade.  Do i need to bump the adaway version in manifest for that to work?

**Comment by 0-kaladin** [comment]
I removed the tag for now, don't want f-droid to build a broken version.  plus need to update internal version in manifest yet.

**Comment by 0-kaladin** [comment]
I see the problem, fixing.

**Pull request merged**
